main:
  wait_time: 3

  # 10 (DEBUG) | 20 (INFO) | 30 (WARNING) | 40 (ERROR) | 50 (CRITICAL)
  logging_level: 20

  # Columns will be presented [Note: Values Of Columns Must Follow The Standard Format]
  columns:
    - Name
    - IP
    - MAC
    - Source
    - Device Type
    - Signal Level

  cached_hosts:
    "ac:49:db:52:bd:f2":
      "Name": "Asmaa"
      "Device Type": PHONE

    "94:16:25:8c:45:4c":
      "Name": "Mostafa"
      "Device Type": PHONE

    "c0:3d:03:26:2f:81":
      "Name": "Mam"
      "Device Type": PHONE

    "28:2d:7f:9f:54:05":
      "Name": "My Iphone"
      "Device Type": PHONE

    "d4:50:ee:57:1a:d6":
      "Name": "Washing machine"
      "Device Type": MACHINE

    "7c:d2:da:b9:47:63":
      "Name": "Dad"
      "Device Type": PHONE

    "fa:5d:81:3b:66:4a":
      "Device Type": TABLET

router:
  protocol: http
  ip: 192.168.1.1
  excluded_macs:
    - b2:19:21:09:96:75
  excluded_ips: []

extender:
  protocol: http
  ip: 192.168.1.207
  excluded_macs: []
  excluded_ips: []

telegram:
  chat_id: 7762730353

windows_notify:
  columns:
    - Name
    - Source
