main:
  wait_time: 3

  # 10 (DEBUG) | 20 (INFO) | 30 (WARNING) | 40 (ERROR) | 50 (CRITICAL)
  logging_level: 30

  # Columns will be presented [Note: Values Of Columns Must Follow The Standard Format]
  columns:
    - Name
    - IP
    - MAC
    - Source
    - Device Type
    - Signal Level

  cached_hosts:
    "0a:1b:2c:3d:4e:5f":
      "Name": "User One"
      "Device Type": PHONE

    "10:22:33:44:55:66":
      "Name": "User Two"
      "Device Type": PHONE

    "11:22:33:44:55:77":
      "Name": "Tablet User"
      "Device Type": PHONE

    "12:34:56:78:9a:bc":
      "Name": "Spare Phone"
      "Device Type": PHONE

    "aa:bb:cc:dd:ee:01":
      "Name": "Office Laptop"
      "Device Type": PC

    "aa:bb:cc:dd:ee:02":
      "Name": "Primary Phone"
      "Device Type": PHONE

    "aa:bb:cc:dd:ee:03":
      "Name": "Smart Washer"
      "Device Type": MACHINE

    "aa:bb:cc:dd:ee:04":
      "Name": "Guest Device"
      "Device Type": PHONE

    "aa:bb:cc:dd:ee:05":
      "Name": "Living Room TV"
      "Device Type": TV

    "aa:bb:cc:dd:ee:06":
      "Device Type": TABLET

router:
  protocol: http
  ip: 192.168.50.1
  excluded_macs:
    # Externder
    - de:ad:be:ef:00:01

    # Asmaa
    # - 0a:1b:2c:3d:4e:5f

    # My Phone
    - aa:bb:cc:dd:ee:02

    # PC
    - de:ad:be:ef:00:02
  excluded_ips: []

extender:
  protocol: http
  ip: 192.168.50.2
  excluded_macs:
    # Asmaa
    # - 0a:1b:2c:3d:4e:5f

    # My Phone
    - aa:bb:cc:dd:ee:02

    # PC
    - de:ad:be:ef:00:02
  excluded_ips: []
  session_time: 3

telegram:
  chat_id: 123456789

windows_notify:
  columns:
    - Name
    - Source
