from dataclasses import dataclass


@dataclass(frozen=True)
class HostColumns:
    ALIAS: str = "Alias"
    HOST_NAME: str = "HostName"
    CURRENT_HOST_NAME: str = "curHostName"
    DEVICE_NAME: str = "DeviceName"
    DEVICE_ICON: str = "DeviceIcon"
    ICON: str = "icon"
    MAC_ADDRESS: str = "PhysAddress"
    IP_ADDRESS: str = "IPAddress"
    IP_ADDRESS_V6: str = "IPAddress6"
    IP_LINK_LOCAL_V6: str = "IPLinkLocalAddress6"
    ADDRESS_SOURCE: str = "AddressSource"
    STATIC_IP: str = "staticIP"
    DHCP_CLIENT: str = "DHCPClient"
    LEASE_TIME_REMAINING: str = "LeaseTimeRemaining"
    EXPIRE_TIME: str = "ExpireTime"
    CLIENT_ID: str = "ClientID"
    CLIENT_DUID: str = "ClientDuid"
    VENDOR_CLASS_ID: str = "VendorClassID"
    USER_CLASS_ID: str = "UserClassID"
    ACTIVE: str = "Active"
    ASSOCIATED_DEVICE: str = "AssociatedDevice"
    LAYER_1_INTERFACE: str = "Layer1Interface"
    LAYER_3_INTERFACE: str = "Layer3Interface"
    CONNECTION_TYPE: str = "X_ZYXEL_ConnectionType"
    CONNECTED_AP: str = "X_ZYXEL_ConnectedAP"
    HOST_TYPE: str = "X_ZYXEL_HostType"
    CAPABILITY_TYPE: str = "X_ZYXEL_CapabilityType"
    LAST_UPDATE: str = "X_ZYXEL_LastUpdate"
    SOFTWARE_VERSION: str = "X_ZYXEL_SoftwareVersion"
    DELETE_LEASE: str = "X_ZYXEL_DeleteLease"
    WIFI_STATUS: str = "X_ZYXEL_WiFiStatus"
    WIFI_NAME: str = "WiFiname"
    RATE_KBPS: str = "X_ZYXEL_PhyRate"
    SIGNAL_STRENGTH: str = "X_ZYXEL_SignalStrength"
    SNR: str = "X_ZYXEL_SNR"
    RSSI: str = "X_ZYXEL_RSSI"
    SUPPORTED_FREQUENCY_BANDS: str = "SupportedFrequencyBands"
    IPV4_ADDRESS_COUNT: str = "IPv4AddressNumberOfEntries"
    IPV6_ADDRESS_COUNT: str = "IPv6AddressNumberOfEntries"
    ADDRESS_V6_SOURCE: str = "X_ZYXEL_Address6Source"
    DHCP6_CLIENT: str = "X_ZYXEL_DHCP6Client"
    DHCP4_POOL_EXIST: str = "dhcp4PoolExist"
    DHCP4_POOL_IID: str = "dhcp4PoolIid"
    DHCP4_STATIC_ADDR_EXIST: str = "dhcp4StaticAddrExist"
    DHCP4_STATIC_ADDR_IID: str = "dhcp4StaticAddrIid"
    DHCP4_STATIC_ADDR_ENABLE: str = "dhcp4StaticAddrEnable"
    DHCP4_STATIC_ADDR: str = "dhcp4StaticAddr"
    DHCP4_STATIC_ADDR_NUM: str = "dhcp4StaticAddrNum"
    DHCP4_STATIC_ADDR_USED_BY_OTHER: str = "dhcp4StaticAddrUsedByOtherHost"
    INTERNET_BLOCKING_ENABLED: str = "Internet_Blocking_Enable"


@dataclass(frozen=True)
class WlanColumns:
    MAC_ADDRESS: str = "Address"
    RATE_KBPS: str = "Rate(kbps)"
    RSSI: str = "RSSI"
    SNR: str = "SNR"
    SIGNAL_LEVEL: str = "Level"
